2022-01-23 13:31:13,400 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-01-23 13:31:13,400 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Julián\Desktop\InstaFoto\instabot\bot\bot.pyc
2022-01-23 13:31:16,520 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-01-23 13:31:16,823 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-01-23 13:31:17,135 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-01-23 13:31:17,391 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-01-23 13:31:17,637 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-01-23 13:31:19,345 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [200]>
2022-01-23 13:31:19,345 - instabot version: 0.117.0 (api) - INFO - Logged-in successfully as 'rtest1235'!
2022-01-23 13:31:19,346 - instabot version: 0.117.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2022-01-23 13:31:19,699 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-01-23 13:31:20,042 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-01-23 13:31:20,318 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: zr/token/result/?device_id=android-ef19382d91bd03a3&token_hash=&custom_device_id=android-ef19382d91bd03a3&fetch_reason=token_expired returned response: <Response [200]>
2022-01-23 13:31:20,600 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: multiple_accounts/get_account_family/ returned response: <Response [200]>
2022-01-23 13:31:20,925 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-01-23 13:31:21,749 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: igtv/browse_feed/?prefetch=1 returned response: <Response [200]>
2022-01-23 13:31:22,030 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: creatives/ar_class/ returned response: <Response [200]>
2022-01-23 13:31:22,512 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2022-01-23 13:31:23,570 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/logout/ returned response: <Response [200]>
2022-01-23 13:31:23,570 - instabot version: 0.117.0 (bot) - INFO - Bot stopped. Worked: 0:00:10.174096
2022-01-23 13:31:23,570 - instabot version: 0.117.0 (bot_checkpoint) - DEBUG - Saving Checkpoint file to: C:\Users\Julián\Desktop\InstaFoto/config/rtest1235.checkpoint
2022-01-23 13:31:23,572 - instabot version: 0.117.0 (bot) - INFO - Total requests: 15
2022-01-23 13:31:23,572 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2022-01-23 13:31:23,572 - instabot version: 0.117.0 (api) - CRITICAL - Not logged in!
2022-01-23 13:31:23,573 - instabot version: 0.117.0 (api_login) - ERROR - Exception raised: Not logged in!
Traceback (most recent call last):
  File "instabot\api\api_login.py", line 188, in login_flow
  File "instabot\api\api.py", line 1653, in media_blocked
  File "instabot\api\api.py", line 486, in send_request
Exception: Not logged in!

2022-01-23 13:31:23,573 - instabot version: 0.117.0 (bot_checkpoint) - DEBUG - Loading Checkpoint file from: C:\Users\Julián\Desktop\InstaFoto/config/rtest1235.checkpoint
